<?php
declare(strict_types=1);

function h(string|null $value): string
{
    return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
}

function app_base_path(): string
{
    static $basePath = null;

    if ($basePath !== null) {
        return $basePath;
    }

    $basePath = '/';
    $scriptPath = (string) ($_SERVER['SCRIPT_NAME'] ?? '');

    if ($scriptPath !== '' && strpos($scriptPath, '/') === 0) {
        $pathParts = explode('/', trim($scriptPath, '/'));
        if (count($pathParts) > 1) {
            // Get the first part (e.g., 'bpo-systemUp' from '/bpo-systemUp/pages/dashboard.php')
            $basePath = '/' . $pathParts[0] . '/';
        }
    }

    return $basePath;
}

function system_setting_fallbacks(): array
{
    return [
        'organization.university_name' => 'Mindoro State University',
        'organization.campus_name' => 'Bongabong Campus',
        'organization.office_name' => 'Production and Business Operation',
        'organization.system_name' => APP_SYSTEM_NAME,
        'organization.logo_path' => APP_LOGO,
        'organization.address' => '',
        'organization.contact_information' => '',
        'display.sidebar_default_state' => 'expanded',
        'display.default_table_rows' => '10',
        'display.dashboard_default_range' => 'daily',
        'display.theme_color' => 'green-gold',
        'reports.receipt_header' => APP_CAMPUS_NAME,
        'reports.or_number_format' => 'OR-{YYYY}-{0000}',
        'reports.prepared_by_default' => '',
        'reports.reviewed_by_default' => 'Department Head / Supervisor',
        'reports.approved_by_default' => 'System Administrator',
        'reports.footer_notes' => 'Generated by the Production and Business Operation Record Management System.',
        'reports.confidentiality_note' => 'This document contains sensitive institutional information. Handle with appropriate care.',
        'security.maximum_login_attempts' => (string) LOGIN_MAX_ATTEMPTS,
        'security.account_lock_duration' => (string) LOGIN_LOCKOUT_MINUTES,
        'security.session_timeout' => (string) ((int) (SESSION_IDLE_TIMEOUT_SECONDS / 60)),
        'security.password_minimum_length' => '8',
        'security.require_strong_password' => '1',
        'security.enable_session_logs' => '1',
    ];
}

function app_settings(?PDO $pdo = null, bool $refresh = false): array
{
    static $cache = null;

    if ($cache !== null && !$refresh) {
        return $cache;
    }

    $settings = system_setting_fallbacks();
    if (!$pdo instanceof PDO) {
        $cache = $settings;
        return $settings;
    }

    try {
        $stmt = $pdo->query('SELECT setting_key, setting_value FROM system_settings');
        foreach ($stmt->fetchAll() as $row) {
            $key = (string) ($row['setting_key'] ?? '');
            if ($key === '') {
                continue;
            }
            $settings[$key] = (string) ($row['setting_value'] ?? '');
        }
    } catch (Throwable $e) {
        error_log('System settings load failed: ' . $e->getMessage());
    }

    $cache = $settings;
    return $settings;
}

function app_setting(?PDO $pdo, string $key, ?string $fallback = null): string
{
    $settings = app_settings($pdo);
    $value = trim((string) ($settings[$key] ?? ''));

    if ($value !== '') {
        return $value;
    }

    $fallbacks = system_setting_fallbacks();
    return $fallback ?? (string) ($fallbacks[$key] ?? '');
}

function organization_profile(?PDO $pdo = null): array
{
    $university = app_setting($pdo, 'organization.university_name', 'Mindoro State University');
    $campus = app_setting($pdo, 'organization.campus_name', 'Bongabong Campus');
    $campusName = trim($university . ' ' . $campus);

    $logoPath = trim(app_setting($pdo, 'organization.logo_path', APP_LOGO));

    // Ensure logo path is web-root absolute so it works from routes like /pages/projects.php
    if ($logoPath === '') {
        $logoPath = APP_LOGO;
    }

    if (!preg_match('#^https?://#i', $logoPath)) {
        $basePath = app_base_path();

        if (strpos($logoPath, 'assets/') === 0) {
            $logoPath = $basePath . $logoPath;
        } elseif (strpos($logoPath, '/') !== 0) {
            $logoPath = $basePath . $logoPath;
        }
    }

    return [
        'university_name' => $university,
        'campus_name' => $campus,
        'office_name' => app_setting($pdo, 'organization.office_name', 'Production and Business Operation'),
        'system_name' => app_setting($pdo, 'organization.system_name', APP_SYSTEM_NAME),
        'logo_path' => $logoPath,
        'address' => app_setting($pdo, 'organization.address', ''),
        'contact_information' => app_setting($pdo, 'organization.contact_information', ''),
        'campus_display_name' => $campusName !== '' ? $campusName : APP_CAMPUS_NAME,
    ];
}

function save_system_settings(PDO $pdo, array $settings, array $user): void
{
    $stmt = $pdo->prepare('INSERT INTO system_settings (setting_key, setting_value, updated_by)
        VALUES (:setting_key, :setting_value, :updated_by)
        ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value), updated_by = VALUES(updated_by)');

    foreach ($settings as $key => $value) {
        $stmt->execute([
            'setting_key' => substr((string) $key, 0, 100),
            'setting_value' => (string) $value,
            'updated_by' => (int) $user['id'],
        ]);
    }

    app_settings($pdo, true);
}

function redirect(string $path): never
{
    header('Location: ' . $path);
    exit;
}

function set_flash(string $type, string $message): void
{
    $_SESSION['flash'] = [
        'type' => $type,
        'message' => $message,
    ];
}

function get_flash(): ?array
{
    if (!isset($_SESSION['flash'])) {
        return null;
    }

    $flash = $_SESSION['flash'];
    unset($_SESSION['flash']);

    return $flash;
}

function csrf_token(): string
{
    if (empty($_SESSION['csrf_token'])) {
        $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
    }

    return $_SESSION['csrf_token'];
}

function verify_csrf(string $token): bool
{
    return isset($_SESSION['csrf_token']) && hash_equals($_SESSION['csrf_token'], $token);
}

function normalize_datetime_input(?string $value): string
{
    $raw = trim((string) $value);
    if ($raw === '') {
        return date('Y-m-d H:i:s');
    }

    $dt = str_replace('T', ' ', $raw);
    if (strlen($dt) === 16) {
        $dt .= ':00';
    }

    $parsed = DateTime::createFromFormat('Y-m-d H:i:s', $dt);
    if ($parsed === false) {
        return date('Y-m-d H:i:s');
    }

    return $parsed->format('Y-m-d H:i:s');
}

function period_bounds(string $period, ?string $referenceDate = null): array
{
    $ref = new DateTimeImmutable($referenceDate ?: 'now');

    switch ($period) {
        case 'daily':
            $start = $ref->setTime(0, 0, 0);
            $end = $ref->setTime(23, 59, 59);
            break;

        case 'weekly':
            $start = $ref->modify('monday this week')->setTime(0, 0, 0);
            $end = $start->modify('+6 days')->setTime(23, 59, 59);
            break;

        case 'monthly':
            $start = $ref->modify('first day of this month')->setTime(0, 0, 0);
            $end = $ref->modify('last day of this month')->setTime(23, 59, 59);
            break;

        case 'annual':
            $start = $ref->setDate((int) $ref->format('Y'), 1, 1)->setTime(0, 0, 0);
            $end = $ref->setDate((int) $ref->format('Y'), 12, 31)->setTime(23, 59, 59);
            break;

        default:
            $start = $ref->setTime(0, 0, 0);
            $end = $ref->setTime(23, 59, 59);
            break;
    }

    return [$start, $end];
}

function money(float|int|string|null $amount): string
{
    return 'PHP ' . number_format((float) $amount, 2);
}

function product_group_label(string $group): string
{
    return match ($group) {
        'igp' => 'Project Items',
        'service' => 'Services',
        default => 'Products',
    };
}

function product_category_label(string $category): string
{
    return match ($category) {
        'school_supply' => 'School Supply',
        'id_supplies' => 'ID Supplies',
        'id_services' => 'ID Services',
        'printing' => 'Printing Service',
        'photocopy' => 'Photocopy Service',
        default => 'Other',
    };
}

function product_category_options(): array
{
    return [
        'school_supply' => 'School Supply',
        'id_supplies' => 'ID Supplies',
        'id_services' => 'ID Services',
        'printing' => 'Printing Service',
        'photocopy' => 'Photocopy Service',
        'other' => 'Other',
    ];
}

function product_display_name(array $product): string
{
    $name = trim((string) ($product['name'] ?? ''));
    $sku = strtoupper(trim((string) ($product['sku'] ?? '')));

    $knownIdNames = [
        'ID-LACE-001' => 'ID Lace',
        'ID-CARD-001' => 'ID Card',
        'ID-PRINT-001' => 'ID Printing',
        'PRINT-ID' => 'ID Printing',
        'ID-REPLACE-001' => 'ID Replacement',
        'ID-FEE-001' => 'ID Processing Fee',
    ];
    if (isset($knownIdNames[$sku])) {
        return $knownIdNames[$sku];
    }

    $normalized = strtolower(preg_replace('/[^a-z0-9]+/i', ' ', $name) ?? '');
    $legacyNames = [
        'provide id' => 'ID Processing Fee',
        'sell id' => 'ID Processing Fee',
        'id service' => 'ID Processing Fee',
        'id items' => 'ID Supplies',
    ];

    return $legacyNames[trim($normalized)] ?? $name;
}

function product_sku_text(array $product): string
{
    $sku = trim((string) ($product['sku'] ?? ''));

    return $sku !== '' ? 'SKU: ' . $sku : 'No SKU';
}

function product_type_label(string $type): string
{
    return $type === 'service' ? 'Service' : 'Product';
}

function product_type_for_category(string $category, string $type): string
{
    if (in_array($category, ['printing', 'photocopy', 'id_services'], true)) {
        return 'service';
    }

    return in_array($type, ['item', 'service'], true) ? $type : 'item';
}

function person_display_label(array $person): string
{
    $parts = [(string) ($person['full_name'] ?? '')];
    if (!empty($person['person_code'])) {
        $parts[] = (string) $person['person_code'];
    }
    if (!empty($person['department'])) {
        $parts[] = (string) $person['department'];
    }
    if (!empty($person['role_or_position'])) {
        $parts[] = (string) $person['role_or_position'];
    }

    return implode(' | ', array_filter($parts, static fn(string $part): bool => trim($part) !== ''));
}

function people_options(PDO $pdo, bool $approvedOnly = true): array
{
    $where = $approvedOnly ? 'WHERE status = "approved"' : '';
    $stmt = $pdo->query('SELECT id, full_name, person_code, department, role_or_position, contact_info, status
        FROM people
        ' . $where . '
        ORDER BY full_name ASC, person_code ASC');

    return $stmt->fetchAll();
}

function find_person(PDO $pdo, int $personId, bool $approvedOnly = true): ?array
{
    if ($personId <= 0) {
        return null;
    }

    $sql = 'SELECT id, full_name, person_code, department, role_or_position, contact_info, status
        FROM people
        WHERE id = :id';
    if ($approvedOnly) {
        $sql .= ' AND status = "approved"';
    }

    $stmt = $pdo->prepare($sql);
    $stmt->execute(['id' => $personId]);
    $person = $stmt->fetch();

    return $person ?: null;
}

function render_person_selector(array $people, string $fieldName, string $inputId, ?int $selectedId = null, string $label = 'Person', bool $required = true, array $options = []): void
{
    $selectedPerson = null;
    foreach ($people as $person) {
        if ((int) $person['id'] === (int) $selectedId) {
            $selectedPerson = $person;
            break;
        }
    }

    $listId = $inputId . '_list';
    $targetDepartment = (string) ($options['department_target'] ?? '');
    $targetName = (string) ($options['name_target'] ?? '');
    $targetCode = (string) ($options['code_target'] ?? '');
    $targetRole = (string) ($options['role_target'] ?? '');
    $placeholder = (string) ($options['placeholder'] ?? 'Search by full name, ID, department, or role');
    $selectedLabel = $selectedPerson ? person_display_label($selectedPerson) : '';

    echo '<div class="person-selector" data-person-selector data-department-target="' . h($targetDepartment) . '" data-name-target="' . h($targetName) . '" data-code-target="' . h($targetCode) . '" data-role-target="' . h($targetRole) . '">';
    echo '<label for="' . h($inputId) . '">' . h($label) . '</label>';
    echo '<input id="' . h($inputId) . '" type="text" list="' . h($listId) . '" value="' . h($selectedLabel) . '" placeholder="' . h($placeholder) . '" data-person-search' . ($required ? ' required' : '') . ' autocomplete="off">';
    echo '<button type="button" class="btn alt mt-2" data-open-modal="' . h((string) ($options['add_modal_id'] ?? 'person-modal')) . '">Add Person</button>';
    echo '<input type="hidden" name="' . h($fieldName) . '" value="' . h($selectedPerson ? (string) $selectedPerson['id'] : '') . '" data-person-id' . ($required ? ' required' : '') . '>';
    echo '<datalist id="' . h($listId) . '">';
    foreach ($people as $person) {
        echo '<option value="' . h(person_display_label($person)) . '" data-person-id="' . (int) $person['id'] . '" data-full-name="' . h((string) $person['full_name']) . '" data-person-code="' . h((string) ($person['person_code'] ?? '')) . '" data-department="' . h((string) ($person['department'] ?? '')) . '" data-role="' . h((string) ($person['role_or_position'] ?? '')) . '"></option>';
    }
    echo '</datalist>';
    echo '<p class="mt-1 text-xs text-slate-500">Select an approved person from the master list.</p>';
    echo '</div>';
}

function render_add_person_modal(array $user, string $returnTo, string $modalId = 'person-modal'): void
{
    $isAdmin = $user['role'] === 'admin';
    echo '<dialog id="' . h($modalId) . '" class="modal">';
    echo '<div class="modal-header">';
    echo '<h3>' . ($isAdmin ? 'Add Person' : 'Request New Person') . '</h3>';
    echo '<button type="button" class="modal-close" data-close-modal aria-label="Close">Close</button>';
    echo '</div>';
    echo '<form method="post">';
    echo '<input type="hidden" name="csrf_token" value="' . h(csrf_token()) . '">';
    echo '<input type="hidden" name="action" value="add_person">';
    echo '<input type="hidden" name="return_to" value="' . h($returnTo) . '">';
    echo '<div class="form-grid">';
    echo '<div><label for="' . h($modalId) . '_full_name">Full Name *</label><input id="' . h($modalId) . '_full_name" name="full_name" required></div>';
    echo '<div><label for="' . h($modalId) . '_person_code">ID or Code</label><input id="' . h($modalId) . '_person_code" name="person_code" placeholder="Student ID or personnel code"></div>';
    echo '<div><label for="' . h($modalId) . '_department">Department</label><input id="' . h($modalId) . '_department" name="department"></div>';
    echo '<div><label for="' . h($modalId) . '_role">Role or Position</label><input id="' . h($modalId) . '_role" name="role_or_position"></div>';
    echo '<div class="field-wide"><label for="' . h($modalId) . '_contact">Contact Info</label><input id="' . h($modalId) . '_contact" name="contact_info"></div>';
    
    if ($isAdmin) {
        echo '<div><label for="' . h($modalId) . '_status">Status</label><select id="' . h($modalId) . '_status" name="status"><option value="active">Active</option><option value="pending">Pending</option><option value="inactive">Inactive</option><option value="rejected">Rejected</option></select></div>';
    } else {
        echo '<p class="text-xs text-slate-600 mt-2">New person records require admin approval before they can be used.</p>';
    }
    
    echo '</div>';
    echo '<div class="modal-actions">';
    echo '<button type="button" class="btn alt" data-close-modal>Cancel</button>';
    echo '<button type="submit">' . ($isAdmin ? 'Save Person' : 'Submit Request') . '</button>';
    echo '</div>';
    echo '</form>';
    echo '</dialog>';
}

function handle_person_post(PDO $pdo, array $user, string $defaultRedirect): bool
{
    $action = (string) ($_POST['action'] ?? '');
    if (!in_array($action, ['add_person', 'update_person'], true)) {
        return false;
    }

    $returnTo = trim((string) ($_POST['return_to'] ?? $defaultRedirect));
    if ($returnTo === '' || str_contains($returnTo, "\n") || str_contains($returnTo, "\r") || preg_match('#^https?://#i', $returnTo)) {
        $returnTo = $defaultRedirect;
    }

    $fullName = trim((string) ($_POST['full_name'] ?? ''));
    $personCode = trim((string) ($_POST['person_code'] ?? ''));
    $department = trim((string) ($_POST['department'] ?? ''));
    $role = trim((string) ($_POST['role_or_position'] ?? ''));
    $contact = trim((string) ($_POST['contact_info'] ?? ''));

    if ($fullName === '') {
        set_flash('error', 'Full name is required.');
        redirect($returnTo);
    }

    if ($action === 'update_person') {
        // Only Admin can update person records
        if ($user['role'] !== 'admin') {
            set_flash('error', 'You do not have permission to perform this action.');
            redirect($returnTo);
        }

        $personId = (int) ($_POST['person_id'] ?? 0);
        $status = (string) ($_POST['status'] ?? 'pending');
        
        if ($personId <= 0 || !in_array($status, ['pending', 'active', 'inactive', 'rejected'], true)) {
            set_flash('error', 'Invalid person update.');
            redirect($returnTo);
        }

        $stmt = $pdo->prepare('SELECT status FROM people WHERE id = :id');
        $stmt->execute(['id' => $personId]);
        $oldPerson = $stmt->fetch();
        if (!$oldPerson) {
            set_flash('error', 'Person not found.');
            redirect($returnTo);
        }
        $oldStatus = $oldPerson['status'];

        $stmt = $pdo->prepare('UPDATE people
            SET full_name = :full_name,
                person_code = :person_code,
                department = :department,
                role_or_position = :role_or_position,
                contact_info = :contact_info,
                status = :status,
                approved_by = CASE WHEN :status = "active" THEN :approved_by ELSE approved_by END,
                approved_at = CASE WHEN :status = "active" THEN COALESCE(approved_at, NOW()) ELSE approved_at END
            WHERE id = :id');
        $stmt->execute([
            'id' => $personId,
            'full_name' => $fullName,
            'person_code' => $personCode !== '' ? $personCode : null,
            'department' => $department !== '' ? $department : null,
            'role_or_position' => $role !== '' ? $role : null,
            'contact_info' => $contact !== '' ? $contact : null,
            'status' => $status,
            'approved_by' => (int) $user['id'],
        ]);

        $auditAction = match($status) {
            'active' => 'person_approved',
            'rejected' => 'person_rejected',
            default => 'person_updated',
        };

        audit_log($pdo, $user, $auditAction, 'people', 'person', $personId, [
            'old_status' => $oldStatus,
            'new_status' => $status,
        ]);

        set_flash('success', 'Person record updated: ' . ucfirst($status) . '.');
        redirect($returnTo);
    }

    // Add new person record
    $isAdmin = $user['role'] === 'admin';
    $status = $isAdmin ? (string) ($_POST['status'] ?? 'active') : 'pending';
    
    if (!in_array($status, ['pending', 'active', 'inactive', 'rejected'], true)) {
        $status = $isAdmin ? 'active' : 'pending';
    }

    $stmt = $pdo->prepare('INSERT INTO people (full_name, person_code, department, role_or_position, contact_info, status, created_by, approved_by, approved_at)
        VALUES (:full_name, :person_code, :department, :role_or_position, :contact_info, :status, :created_by, :approved_by, :approved_at)');
    $stmt->execute([
        'full_name' => $fullName,
        'person_code' => $personCode !== '' ? $personCode : null,
        'department' => $department !== '' ? $department : null,
        'role_or_position' => $role !== '' ? $role : null,
        'contact_info' => $contact !== '' ? $contact : null,
        'status' => $status,
        'created_by' => (int) $user['id'],
        'approved_by' => $status === 'active' ? (int) $user['id'] : null,
        'approved_at' => $status === 'active' ? date('Y-m-d H:i:s') : null,
    ]);
    $personId = (int) $pdo->lastInsertId();
    audit_log($pdo, $user, 'create_person', 'people', 'person', $personId, ['status' => $status]);
    
    if ($status === 'active') {
        set_flash('success', 'Person record saved.');
    } else {
        set_flash('success', 'Person request submitted for admin approval.');
    }
    
    redirect($returnTo);
}

function product_group_for_type(string $category, string $type, string $group): string
{
    if ($type === 'service' || in_array($category, ['printing', 'photocopy', 'id_services'], true)) {
        return 'service';
    }

    return in_array($group, ['product', 'igp', 'service'], true) ? $group : 'product';
}

function inventory_stock_in(PDO $pdo, int $productId, int $quantity, float $unitCost, string $receivedDate, ?string $referenceNo, ?string $notes, ?array $user = null, string $sourceType = 'stock_in'): int
{
    if ($quantity <= 0) {
        return 0;
    }

    $productStmt = $pdo->prepare('SELECT id, type FROM products WHERE id = :id AND is_active = 1 FOR UPDATE');
    $productStmt->execute(['id' => $productId]);
    $product = $productStmt->fetch();
    if (!$product || $product['type'] !== 'item') {
        throw new RuntimeException('Stock can only be added to active inventory items.');
    }

    $batchCode = ($sourceType === 'opening_balance' ? 'OPEN-' : 'BATCH-') . $productId . '-' . date('YmdHis');
    $insertBatch = $pdo->prepare('INSERT INTO inventory_stock_batches (product_id, batch_code, received_date, quantity_received, quantity_remaining, unit_cost, source_type, reference_no, notes, created_by)
        VALUES (:product_id, :batch_code, :received_date, :quantity_received, :quantity_remaining, :unit_cost, :source_type, :reference_no, :notes, :created_by)');
    $insertBatch->execute([
        'product_id' => $productId,
        'batch_code' => $batchCode,
        'received_date' => $receivedDate,
        'quantity_received' => $quantity,
        'quantity_remaining' => $quantity,
        'unit_cost' => $unitCost,
        'source_type' => substr($sourceType, 0, 40),
        'reference_no' => $referenceNo !== '' ? $referenceNo : null,
        'notes' => $notes !== '' ? $notes : null,
        'created_by' => isset($user['id']) ? (int) $user['id'] : current_user_id_from_session(),
    ]);
    $batchId = (int) $pdo->lastInsertId();

    $insertMovement = $pdo->prepare('INSERT INTO inventory_stock_movements (product_id, batch_id, movement_date, movement_type, quantity_change, unit_cost, total_cost, reference_no, notes, created_by)
        VALUES (:product_id, :batch_id, :movement_date, "stock_in", :quantity_change, :unit_cost, :total_cost, :reference_no, :notes, :created_by)');
    $insertMovement->execute([
        'product_id' => $productId,
        'batch_id' => $batchId,
        'movement_date' => $receivedDate,
        'quantity_change' => $quantity,
        'unit_cost' => $unitCost,
        'total_cost' => $unitCost * $quantity,
        'reference_no' => $referenceNo !== '' ? $referenceNo : null,
        'notes' => $notes !== '' ? $notes : null,
        'created_by' => isset($user['id']) ? (int) $user['id'] : current_user_id_from_session(),
    ]);

    $updateProduct = $pdo->prepare('UPDATE products SET stock_qty = stock_qty + :quantity WHERE id = :id');
    $updateProduct->execute([
        'quantity' => $quantity,
        'id' => $productId,
    ]);

    return $batchId;
}

function inventory_fifo_issue(PDO $pdo, int $productId, int $quantity, string $movementDate, string $movementType, ?string $referenceNo, ?string $notes, ?array $user = null): array
{
    if ($quantity <= 0) {
        throw new RuntimeException('Quantity must be greater than zero.');
    }

    if (!in_array($movementType, ['sale', 'stock_out', 'adjustment'], true)) {
        throw new RuntimeException('Invalid stock movement type.');
    }

    $productStmt = $pdo->prepare('SELECT id, type, stock_qty FROM products WHERE id = :id AND is_active = 1 FOR UPDATE');
    $productStmt->execute(['id' => $productId]);
    $product = $productStmt->fetch();
    if (!$product || $product['type'] !== 'item') {
        throw new RuntimeException('FIFO stock can only be issued from active inventory items.');
    }

    if ((int) $product['stock_qty'] < $quantity) {
        throw new RuntimeException('Insufficient stock.');
    }

    $batchStmt = $pdo->prepare('SELECT id, quantity_remaining, unit_cost
        FROM inventory_stock_batches
        WHERE product_id = :product_id AND quantity_remaining > 0
        ORDER BY received_date ASC, id ASC
        FOR UPDATE');
    $batchStmt->execute(['product_id' => $productId]);
    $batches = $batchStmt->fetchAll();

    $remaining = $quantity;
    $totalCost = 0.0;
    $movementIds = [];
    $updateBatch = $pdo->prepare('UPDATE inventory_stock_batches SET quantity_remaining = quantity_remaining - :quantity WHERE id = :id AND quantity_remaining >= :required_quantity');
    $insertMovement = $pdo->prepare('INSERT INTO inventory_stock_movements (product_id, batch_id, movement_date, movement_type, quantity_change, unit_cost, total_cost, reference_no, notes, created_by)
        VALUES (:product_id, :batch_id, :movement_date, :movement_type, :quantity_change, :unit_cost, :total_cost, :reference_no, :notes, :created_by)');

    foreach ($batches as $batch) {
        if ($remaining <= 0) {
            break;
        }

        $available = (int) $batch['quantity_remaining'];
        $take = min($available, $remaining);
        if ($take <= 0) {
            continue;
        }

        $unitCost = (float) $batch['unit_cost'];
        $layerCost = $unitCost * $take;
        $updateBatch->execute([
            'quantity' => $take,
            'required_quantity' => $take,
            'id' => (int) $batch['id'],
        ]);
        if ($updateBatch->rowCount() === 0) {
            throw new RuntimeException('FIFO stock layer update failed.');
        }

        $insertMovement->execute([
            'product_id' => $productId,
            'batch_id' => (int) $batch['id'],
            'movement_date' => $movementDate,
            'movement_type' => $movementType,
            'quantity_change' => -$take,
            'unit_cost' => $unitCost,
            'total_cost' => $layerCost,
            'reference_no' => $referenceNo !== '' ? $referenceNo : null,
            'notes' => $notes !== '' ? $notes : null,
            'created_by' => isset($user['id']) ? (int) $user['id'] : current_user_id_from_session(),
        ]);
        $movementIds[] = (int) $pdo->lastInsertId();
        $totalCost += $layerCost;
        $remaining -= $take;
    }

    if ($remaining > 0) {
        throw new RuntimeException('Not enough FIFO stock layers.');
    }

    $updateProduct = $pdo->prepare('UPDATE products SET stock_qty = stock_qty - :quantity WHERE id = :id AND stock_qty >= :required_quantity');
    $updateProduct->execute([
        'quantity' => $quantity,
        'required_quantity' => $quantity,
        'id' => $productId,
    ]);
    if ($updateProduct->rowCount() === 0) {
        throw new RuntimeException('Product stock update failed.');
    }

    return [
        'total_cost' => $totalCost,
        'unit_cost' => $quantity > 0 ? $totalCost / $quantity : 0,
        'movement_ids' => $movementIds,
    ];
}

function date_filter_bounds(string $from, string $to): array
{
    $fromDate = DateTimeImmutable::createFromFormat('Y-m-d H:i:s', $from . ' 00:00:00') ?: new DateTimeImmutable('first day of this month 00:00:00');
    $toDate = DateTimeImmutable::createFromFormat('Y-m-d H:i:s', $to . ' 00:00:00') ?: new DateTimeImmutable('today 00:00:00');

    return [
        $fromDate->format('Y-m-d 00:00:00'),
        $toDate->modify('+1 day')->format('Y-m-d 00:00:00'),
    ];
}

function prefix_search_param(string $value): string
{
    return str_replace(['%', '_'], ['\\%', '\\_'], trim($value)) . '%';
}

function project_account_meta_set(PDO $pdo, int $accountId, string $key, ?string $value): void
{
    $stmt = $pdo->prepare('INSERT INTO project_account_meta (account_id, meta_key, meta_value)
        VALUES (:account_id, :meta_key, :meta_value)
        ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value)');
    $stmt->execute([
        'account_id' => $accountId,
        'meta_key' => substr($key, 0, 80),
        'meta_value' => $value,
    ]);
}

function project_entry_meta_set(PDO $pdo, int $entryId, string $key, ?string $value): void
{
    $stmt = $pdo->prepare('INSERT INTO project_entry_meta (entry_id, meta_key, meta_value)
        VALUES (:entry_id, :meta_key, :meta_value)
        ON DUPLICATE KEY UPDATE meta_value = VALUES(meta_value)');
    $stmt->execute([
        'entry_id' => $entryId,
        'meta_key' => substr($key, 0, 80),
        'meta_value' => $value,
    ]);
}

function project_meta_decimal(mixed $value): float
{
    if ($value === null || $value === '') {
        return 0.0;
    }

    return (float) $value;
}

function user_can(array $user, string $permission): bool
{
    $role = strtolower((string) ($user['role'] ?? ''));
    $permissions = [
        'admin' => ['*'],
        'staff' => [
            'view_dashboard',
            'view_operations',
            'record_operations',
            'view_reports',
        ],
    ];

    $allowed = $permissions[$role] ?? [];

    return in_array('*', $allowed, true) || in_array($permission, $allowed, true);
}

function require_permission(array $user, string $permission, string $fallback = 'dashboard.php'): void
{
    if (user_can($user, $permission)) {
        return;
    }

    set_flash('error', 'Your account does not have permission to access that function.');
    redirect($fallback);
}

function current_request_ip(): string
{
    $ip = (string) ($_SERVER['REMOTE_ADDR'] ?? 'unknown');

    return substr($ip !== '' ? $ip : 'unknown', 0, 45);
}

function current_user_id_from_session(): ?int
{
    return !empty($_SESSION['user_id']) ? (int) $_SESSION['user_id'] : null;
}

function encode_log_context(array|string|null $context): ?string
{
    if ($context === null) {
        return null;
    }

    if (is_string($context)) {
        return $context;
    }

    $encoded = json_encode($context, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

    return $encoded === false ? null : $encoded;
}

function audit_log(PDO $pdo, ?array $user, string $action, string $module, ?string $entityType = null, int|string|null $entityId = null, array|string|null $details = null): void
{
    try {
        $stmt = $pdo->prepare('INSERT INTO audit_logs (user_id, action, module, entity_type, entity_id, details, ip_address)
            VALUES (:user_id, :action, :module, :entity_type, :entity_id, :details, :ip_address)');
        $stmt->execute([
            'user_id' => isset($user['id']) ? (int) $user['id'] : current_user_id_from_session(),
            'action' => substr($action, 0, 80),
            'module' => substr($module, 0, 80),
            'entity_type' => $entityType !== null ? substr($entityType, 0, 80) : null,
            'entity_id' => $entityId !== null ? substr((string) $entityId, 0, 80) : null,
            'details' => encode_log_context($details),
            'ip_address' => current_request_ip(),
        ]);
    } catch (Throwable $e) {
        error_log('Audit log failed: ' . $e->getMessage());
    }
}

function log_system_issue(PDO $pdo, string $severity, string $message, array|string|null $context = null, ?array $user = null): void
{
    $validSeverities = ['notice', 'warning', 'error', 'critical'];
    if (!in_array($severity, $validSeverities, true)) {
        $severity = 'error';
    }

    try {
        $stmt = $pdo->prepare('INSERT INTO system_error_logs (user_id, severity, message, context, ip_address)
            VALUES (:user_id, :severity, :message, :context, :ip_address)');
        $stmt->execute([
            'user_id' => isset($user['id']) ? (int) $user['id'] : current_user_id_from_session(),
            'severity' => $severity,
            'message' => substr($message, 0, 255),
            'context' => encode_log_context($context),
            'ip_address' => current_request_ip(),
        ]);
    } catch (Throwable $e) {
        error_log('System issue log failed: ' . $e->getMessage());
    }
}

function configure_error_logging(PDO $pdo): void
{
    set_error_handler(static function (int $severity, string $message, string $file, int $line) use ($pdo): bool {
        if (!(error_reporting() & $severity)) {
            return false;
        }

        $level = in_array($severity, [E_USER_ERROR, E_RECOVERABLE_ERROR], true) ? 'error' : 'warning';
        log_system_issue($pdo, $level, $message, [
            'file' => $file,
            'line' => $line,
            'severity' => $severity,
        ]);

        return false;
    });

    register_shutdown_function(static function () use ($pdo): void {
        $error = error_get_last();
        if (!$error || !in_array((int) $error['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR], true)) {
            return;
        }

        log_system_issue($pdo, 'critical', (string) $error['message'], [
            'file' => (string) $error['file'],
            'line' => (int) $error['line'],
            'type' => (int) $error['type'],
        ]);
    });
}

function page_param(string $name = 'page'): int
{
    return max(1, (int) ($_GET[$name] ?? 1));
}

function pagination_meta(int $totalRows, int $page, int $perPage): array
{
    $totalPages = max(1, (int) ceil($totalRows / max(1, $perPage)));
    $page = min(max(1, $page), $totalPages);

    return [
        'page' => $page,
        'per_page' => $perPage,
        'total_rows' => $totalRows,
        'total_pages' => $totalPages,
        'offset' => ($page - 1) * $perPage,
    ];
}

function pagination_row_bounds(array $pagination): array
{
    $first = (int) $pagination['offset'] + 1;
    $last = (int) $pagination['offset'] + (int) $pagination['per_page'];

    return [$first, $last];
}

function pagination_url(int $page, string $param = 'page'): string
{
    $query = $_GET;
    $query[$param] = $page;
    $script = basename((string) ($_SERVER['PHP_SELF'] ?? 'index.php'));

    return $script . '?' . http_build_query($query);
}

function render_pagination(array $pagination, string $param = 'page'): void
{
    if ((int) $pagination['total_pages'] <= 1) {
        return;
    }

    $page = (int) $pagination['page'];
    $totalPages = (int) $pagination['total_pages'];
    $start = max(1, $page - 2);
    $end = min($totalPages, $page + 2);

    echo '<nav class="pagination" aria-label="Pagination">';
    echo '<a class="page-link' . ($page <= 1 ? ' disabled' : '') . '" href="' . h(pagination_url(max(1, $page - 1), $param)) . '">Previous</a>';
    for ($i = $start; $i <= $end; $i++) {
        echo '<a class="page-link' . ($i === $page ? ' active' : '') . '" href="' . h(pagination_url($i, $param)) . '">' . h((string) $i) . '</a>';
    }
    echo '<a class="page-link' . ($page >= $totalPages ? ' disabled' : '') . '" href="' . h(pagination_url(min($totalPages, $page + 1), $param)) . '">Next</a>';
    echo '</nav>';
}

// Approval request functions

function create_approval_request(
    PDO $pdo,
    int $requesterId,
    string $module,
    string $actionType,
    ?string $entityType = null,
    ?string $entityId = null,
    array|null $oldValue = null,
    array|null $newValue = null
): int {
    try {
        $stmt = $pdo->prepare('INSERT INTO approval_requests
            (requester_id, module, action_type, entity_type, entity_id, old_value, new_value, status, created_at, updated_at)
            VALUES (:requester_id, :module, :action_type, :entity_type, :entity_id, :old_value, :new_value, "pending", NOW(), NOW())');
        
        $stmt->execute([
            'requester_id' => $requesterId,
            'module' => substr($module, 0, 80),
            'action_type' => substr($actionType, 0, 80),
            'entity_type' => $entityType !== null ? substr($entityType, 0, 80) : null,
            'entity_id' => $entityId !== null ? substr((string) $entityId, 0, 80) : null,
            'old_value' => $oldValue !== null ? json_encode($oldValue, JSON_UNESCAPED_UNICODE) : null,
            'new_value' => $newValue !== null ? json_encode($newValue, JSON_UNESCAPED_UNICODE) : null,
        ]);

        $approvalId = (int) $pdo->lastInsertId();
        
        // Log the approval request creation
        audit_log($pdo, ['id' => $requesterId], 'approval_request_created', $module, $entityType, $entityId, [
            'action_type' => $actionType,
            'approval_id' => $approvalId,
        ]);

        return $approvalId;
    } catch (Throwable $e) {
        error_log('Approval request creation failed: ' . $e->getMessage());
        throw $e;
    }
}

function get_approval_request(PDO $pdo, int $approvalId): ?array
{
    $stmt = $pdo->prepare('SELECT ar.*, u.full_name AS requester_name, u.role AS requester_role,
        du.full_name AS decided_by_name
        FROM approval_requests ar
        LEFT JOIN users u ON u.id = ar.requester_id
        LEFT JOIN users du ON du.id = ar.decided_by_id
        WHERE ar.id = :id');
    
    $stmt->execute(['id' => $approvalId]);
    $result = $stmt->fetch();
    
    if ($result) {
        if ($result['old_value']) {
            $result['old_value'] = json_decode($result['old_value'], true);
        }
        if ($result['new_value']) {
            $result['new_value'] = json_decode($result['new_value'], true);
        }
    }
    
    return $result ?: null;
}

function list_approval_requests(PDO $pdo, ?string $status = 'pending', int $page = 1, int $limit = 50): array
{
    $offset = max(0, ($page - 1) * $limit);
    
    $query = 'SELECT ar.*, u.full_name AS requester_name, u.role AS requester_role,
        du.full_name AS decided_by_name
        FROM approval_requests ar
        LEFT JOIN users u ON u.id = ar.requester_id
        LEFT JOIN users du ON du.id = ar.decided_by_id';
    
    $params = [];
    
    if ($status !== null) {
        $query .= ' WHERE ar.status = :status';
        $params['status'] = $status;
    }
    
    $query .= ' ORDER BY ar.created_at DESC LIMIT :offset, :limit';
    
    $stmt = $pdo->prepare($query);
    foreach ($params as $key => $value) {
        $stmt->bindValue(':' . $key, $value);
    }
    $stmt->bindValue(':offset', $offset, PDO::PARAM_INT);
    $stmt->bindValue(':limit', $limit, PDO::PARAM_INT);
    $stmt->execute();
    
    $results = [];
    while ($row = $stmt->fetch()) {
        if ($row['old_value']) {
            $row['old_value'] = json_decode($row['old_value'], true);
        }
        if ($row['new_value']) {
            $row['new_value'] = json_decode($row['new_value'], true);
        }
        $results[] = $row;
    }
    
    return $results;
}

function approve_approval_request(PDO $pdo, int $approvalId, int $deciderId, ?string $remarks = null): bool
{
    try {
        $stmt = $pdo->prepare('UPDATE approval_requests
            SET status = "approved", admin_decision = "approved", admin_remarks = :remarks,
                decision_date = NOW(), decided_by_id = :decided_by_id, updated_at = NOW()
            WHERE id = :id AND status = "pending"');
        
        $stmt->execute([
            'id' => $approvalId,
            'decided_by_id' => $deciderId,
            'remarks' => $remarks,
        ]);
        
        if ($stmt->rowCount() > 0) {
            $request = get_approval_request($pdo, $approvalId);
            audit_log($pdo, ['id' => $deciderId], 'approval_request_approved', $request['module'], $request['entity_type'], $request['entity_id'], [
                'approval_id' => $approvalId,
                'action_type' => $request['action_type'],
            ]);
            return true;
        }
        return false;
    } catch (Throwable $e) {
        error_log('Approval request approval failed: ' . $e->getMessage());
        throw $e;
    }
}

function reject_approval_request(PDO $pdo, int $approvalId, int $deciderId, ?string $remarks = null): bool
{
    try {
        $stmt = $pdo->prepare('UPDATE approval_requests
            SET status = "rejected", admin_decision = "rejected", admin_remarks = :remarks,
                decision_date = NOW(), decided_by_id = :decided_by_id, updated_at = NOW()
            WHERE id = :id AND status = "pending"');
        
        $stmt->execute([
            'id' => $approvalId,
            'decided_by_id' => $deciderId,
            'remarks' => $remarks,
        ]);
        
        if ($stmt->rowCount() > 0) {
            $request = get_approval_request($pdo, $approvalId);
            audit_log($pdo, ['id' => $deciderId], 'approval_request_rejected', $request['module'], $request['entity_type'], $request['entity_id'], [
                'approval_id' => $approvalId,
                'action_type' => $request['action_type'],
            ]);
            return true;
        }
        return false;
    } catch (Throwable $e) {
        error_log('Approval request rejection failed: ' . $e->getMessage());
        throw $e;
    }
}

function request_revision_on_approval(PDO $pdo, int $approvalId, int $deciderId, ?string $remarks = null): bool
{
    try {
        $stmt = $pdo->prepare('UPDATE approval_requests
            SET status = "needs_revision", admin_decision = "needs_revision", admin_remarks = :remarks,
                decision_date = NOW(), decided_by_id = :decided_by_id, updated_at = NOW()
            WHERE id = :id AND status = "pending"');
        
        $stmt->execute([
            'id' => $approvalId,
            'decided_by_id' => $deciderId,
            'remarks' => $remarks,
        ]);
        
        if ($stmt->rowCount() > 0) {
            $request = get_approval_request($pdo, $approvalId);
            audit_log($pdo, ['id' => $deciderId], 'approval_request_revision_requested', $request['module'], $request['entity_type'], $request['entity_id'], [
                'approval_id' => $approvalId,
                'action_type' => $request['action_type'],
            ]);
            return true;
        }
        return false;
    } catch (Throwable $e) {
        error_log('Approval request revision request failed: ' . $e->getMessage());
        throw $e;
    }
}

function count_pending_approvals(PDO $pdo): int
{
    $stmt = $pdo->query('SELECT COUNT(*) FROM approval_requests WHERE status = "pending"');
    return (int) $stmt->fetchColumn();
}
